import React, { createContext, useState, useEffect } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        "welcome": "Welcome to VyapaarSetu",
        "login": "Login",
        "register": "Register",
        "search": "Search vendors...",
        "near_me": "Near Me",
        "hero_title_1": "Connect. Scale. Dominate.",
        "hero_title_2": "The Intelligent Local Network.",
        "hero_subtitle": "VyapaarSetu — an AI-powered hyperlocal marketplace connecting local vendors and customers with precision. Take your business online in minutes.",
        "nav_platform": "Platform",
        "nav_protocol": "Protocol",
        "nav_network": "Network",
        "nav_login": "Login",
        "nav_register": "Register",
        "marketplace_title": "Hyperlocal Grid",
        "marketplace_subtitle": "Connect with nearby verified vendors instantly.",
        "search_placeholder": "Search local inventory...",
        "locate_me": "LOCATE ME",
        "point_locked": "POINT LOCKED",
        "ai_search": "AI SEARCH",
        "no_inventory": "NO MATCHING INVENTORY FOUND IN CURRENT RADIUS.",
        "scanning": "SCANNING LOCAL NODES...",
        "features_title": "Core Modules",
        "features_ai": "AI DISCOVERY",
        "features_ai_desc": "Neural-network powered product matching based on proximity and behavioral data.",
        "features_sync": "REAL-TIME SYNC",
        "features_sync_desc": "Bi-directional WebSocket streams for instantaneous order state replication.",
        "features_analytics": "PREDICTIVE ANALYTICS",
        "features_analytics_desc": "Machine learning models forecasting local demand surges for vendors.",
        "how_title": "System Architecture",
        "how_step1_title": "Register Node",
        "how_step1_desc": "Connect your local inventory to the VyapaarSetu network in under 3 minutes via smartphone.",
        "how_step2_title": "AI Matchmaking",
        "how_step2_desc": "Our engine analyzes local search intent and surfaces your products to nearby high-intent buyers.",
        "how_step3_title": "Execute via UPI",
        "how_step3_desc": "Receive direct, zero-friction payments and instant WhatsApp dispatch alerts automatically.",
        "stats_nodes": "Active Nodes",
        "stats_transactions": "Daily Transactions",
        "stats_latency": "System Latency",
        "faq_title": "Knowledge Base",
        "faq_q1": "Do I need technical skills to join?",
        "faq_a1": "None. If you can use WhatsApp, you can use VyapaarSetu. Our onboarding requires only your business name, location, and a quick inventory scan to get started.",
        "faq_q2": "How are UPI payments handled?",
        "faq_a2": "We integrate directly with native UPI apps (GPay, PhonePe, Paytm). Payments go directly from the customer's account to your linked business bank account with zero middleman holding periods.",
        "faq_q3": "What if my store is hard to find?",
        "faq_a3": "Our AI strictly maps hyperlocal proximity. We connect you exactly with customers within 5km radius who are actively searching for what you sell, effectively bypassing physical location visibility issues.",
        "faq_q4": "Are there hidden subscription fees?",
        "faq_a4": "No. You pay a micro-transaction fee only when a successful order is processed. Platform infrastructure and WhatsApp updates are entirely free for verified vendors.",
        "cta_title": "Join VyapaarSetu",
        "cta_subtitle": "Join the fastest growing localized network and digitize your operations instantly.",
        "cta_button": "GET STARTED",
        "social_vendors": "10,000+ Local Vendors",
        "social_uptime": "99.9% Uptime",
        "social_processed": "₹50Cr+ Processed",
        "social_discovery": "2M+ Monthly Discovery",
        "social_rating": "4.9★ Vendor Rating",
        "footer_tagline": "AI-powered intelligence linking local vendors directly to high-intent nearby customers.",
        "footer_system": "SYSTEM OPERATIONAL",
        "footer_network": "NETWORK",
        "footer_vendor_login": "Vendor Login",
        "footer_agent_access": "Agent Access",
        "footer_documentation": "Documentation",
        "footer_status": "Status",
        "footer_legal": "LEGAL",
        "footer_terms": "Terms of Service",
        "footer_privacy": "Privacy Policy",
        "footer_data": "Data Protocol",
        "footer_copyright": "VyapaarSetu Network. All Rights Reserved.",
        "login_email": "EMAIL ADDRESS",
        "login_password": "PASSWORD",
        "login_submit": "ACCESS TERMINAL",
        "login_new_user": "NEW TO VYAPAARSETU?",
        "login_register_link": "REGISTER NODE",
        "register_customer": "CUSTOMER",
        "register_vendor": "VENDOR",
        "register_fullname": "FULL NAME",
        "register_email": "EMAIL ADDRESS",
        "register_password": "PASSWORD",
        "register_business": "BUSINESS NAME",
        "register_submit": "REGISTER",
        "register_existing": "EXISTING USER?",
        "register_login_link": "LOGIN RECORD"
      }
    },
    hi: {
      translation: {
        "welcome": "VyapaarSetu में आपका स्वागत है",
        "login": "लॉग इन करें",
        "register": "रजिस्टर करें",
        "search": "विक्रेताओं को खोजें...",
        "near_me": "मेरे पास",
        "hero_title_1": "जुड़ें। बढ़ें। छा जाएँ।",
        "hero_title_2": "स्मार्ट लोकल नेटवर्क।",
        "hero_subtitle": "VyapaarSetu — एक AI-संचालित हाइपरलोकल मार्केटप्लेस जो स्थानीय विक्रेताओं और ग्राहकों को सटीकता से जोड़ता है। अपने व्यवसाय को मिनटों में ऑनलाइन ले जाएं।",
        "nav_platform": "प्लेटफ़ॉर्म",
        "nav_protocol": "प्रोटोकॉल",
        "nav_network": "नेटवर्क",
        "nav_login": "लॉग इन",
        "nav_register": "रजिस्टर",
        "marketplace_title": "हाइपरलोकल ग्रिड",
        "marketplace_subtitle": "आस-पास के सत्यापित विक्रेताओं से तुरंत जुड़ें।",
        "search_placeholder": "स्थानीय इन्वेंट्री खोजें...",
        "locate_me": "मुझे खोजें",
        "point_locked": "स्थान लॉक किया गया",
        "ai_search": "AI खोज",
        "no_inventory": "वर्तमान दायरे में कोई इन्वेंट्री नहीं मिली।",
        "scanning": "स्थानीय नोड स्कैन हो रहे हैं...",
        "features_title": "मुख्य मॉड्यूल",
        "features_ai": "AI डिस्कवरी",
        "features_ai_desc": "निकटता और व्यवहार डेटा के आधार पर न्यूरल-नेटवर्क संचालित उत्पाद मिलान।",
        "features_sync": "रीयल-टाइम सिंक",
        "features_sync_desc": "तत्काल ऑर्डर स्थिति रेप्लिकेशन के लिए द्वि-दिशात्मक वेबसॉकेट स्ट्रीम।",
        "features_analytics": "प्रेडिक्टिव एनालिटिक्स",
        "features_analytics_desc": "स्थानीय मांग में वृद्धि का पूर्वानुमान लगाने वाले मशीन लर्निंग मॉडल।",
        "how_title": "सिस्टम आर्किटेक्चर",
        "how_step1_title": "नोड पंजीकरण",
        "how_step1_desc": "अपनी स्थानीय इन्वेंट्री को 3 मिनट से भी कम समय में स्मार्टफोन से VyapaarSetu नेटवर्क से जोड़ें।",
        "how_step2_title": "AI मैचमेकिंग",
        "how_step2_desc": "हमारा इंजन स्थानीय खोज इरादे का विश्लेषण करता है और आपके उत्पादों को नज़दीकी खरीदारों तक पहुँचाता है।",
        "how_step3_title": "UPI से भुगतान",
        "how_step3_desc": "सीधे, बिना किसी बाधा के भुगतान प्राप्त करें और तुरंत WhatsApp अलर्ट स्वचालित रूप से पाएं।",
        "stats_nodes": "सक्रिय नोड",
        "stats_transactions": "दैनिक लेन-देन",
        "stats_latency": "सिस्टम लेटेंसी",
        "faq_title": "ज्ञान भंडार",
        "faq_q1": "क्या मुझे जुड़ने के लिए तकनीकी कौशल की आवश्यकता है?",
        "faq_a1": "बिल्कुल नहीं। यदि आप व्हाट्सएप का उपयोग कर सकते हैं, तो आप व्यापार सेतु का उपयोग कर सकते हैं। हमारा सेटअप बहुत आसान है।",
        "faq_q2": "UPI भुगतान कैसे संभाले जाते हैं?",
        "faq_a2": "हम सीधे मूल UPI ऐप के साथ एकीकृत होते हैं। भुगतान सीधे ग्राहक के खाते से आपके लिंक किए गए व्यवसाय बैंक खाते में जाता है।",
        "faq_q3": "अगर मेरी दुकान खोजना मुश्किल हो तो क्या होगा?",
        "faq_a3": "हमारा AI सख्ती से हाइपरलोकल निकटता को मैप करता है। हम आपको 5 किमी के दायरे में ग्राहकों के साथ ठीक से जोड़ते हैं।",
        "faq_q4": "क्या कोई छिपी हुई सदस्यता शुल्क है?",
        "faq_a4": "नहीं। आप केवल एक सफल ऑर्डर संसाधित होने पर एक सूक्ष्म लेनदेन शुल्क का भुगतान करते हैं।",
        "cta_title": "VyapaarSetu से जुड़ें",
        "cta_subtitle": "सबसे तेजी से बढ़ते स्थानीय नेटवर्क से जुड़ें और तुरंत अपने संचालन को डिजिटल बनाएं।",
        "cta_button": "शुरू करें",
        "social_vendors": "10,000+ स्थानीय विक्रेता",
        "social_uptime": "99.9% अपटाइम",
        "social_processed": "₹50करोड़+ प्रोसेस्ड",
        "social_discovery": "20 लाख+ मासिक खोज",
        "social_rating": "4.9★ विक्रेता रेटिंग",
        "footer_tagline": "AI-संचालित बुद्धिमत्ता जो स्थानीय विक्रेताओं को सीधे नज़दीकी ग्राहकों से जोड़ती है।",
        "footer_system": "सिस्टम चालू है",
        "footer_network": "नेटवर्क",
        "footer_vendor_login": "विक्रेता लॉग इन",
        "footer_agent_access": "एजेंट एक्सेस",
        "footer_documentation": "दस्तावेज़ीकरण",
        "footer_status": "स्थिति",
        "footer_legal": "कानूनी",
        "footer_terms": "सेवा की शर्तें",
        "footer_privacy": "गोपनीयता नीति",
        "footer_data": "डेटा प्रोटोकॉल",
        "footer_copyright": "VyapaarSetu नेटवर्क। सर्वाधिकार सुरक्षित।",
        "login_email": "ईमेल पता",
        "login_password": "पासवर्ड",
        "login_submit": "लॉग इन करें",
        "login_new_user": "VyapaarSetu में नए हैं?",
        "login_register_link": "रजिस्टर करें",
        "register_customer": "ग्राहक",
        "register_vendor": "विक्रेता",
        "register_fullname": "पूरा नाम",
        "register_email": "ईमेल पता",
        "register_password": "पासवर्ड",
        "register_business": "व्यवसाय का नाम",
        "register_submit": "रजिस्टर करें",
        "register_existing": "पहले से उपयोगकर्ता हैं?",
        "register_login_link": "लॉग इन करें"
      }
    }
  },
  lng: localStorage.getItem('language') || 'en',
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false
  }
});

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(i18n.language);

  const changeLanguage = (lang) => {
    i18n.changeLanguage(lang);
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t: i18n.t }}>
      {children}
    </LanguageContext.Provider>
  );
};
